const { description } = require("../../package");

module.exports = {
  /* TÍTULO - Ref：https://v1.vuepress.vuejs.org/config/#title*/
  title: "Documentación API Banking",

  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#description
   */
  description: description,
  markdown: {
    lineNumbers: true,
  },

  /**
   * Extra tags to be injected to the page HTML `<head>`
   *
   * ref：https://v1.vuepress.vuejs.org/config/#head
   */
  head: [
    
    ['link', { rel: 'icon', href: './img/logo_nuevo_mini.png' }],
    ["meta", { name: "theme-color", content: "#C8070A" }],
    ["meta", { name: "apple-mobile-web-app-capable", content: "yes" }],
    [
      "meta",
      { name: "apple-mobile-web-app-status-bar-style", content: "black" },
    ],
    ['link', { rel: 'stylesheet', href: '/styles/style.css' }],
  ],

  /**
   * Theme configuration, here is the default theme configuration for VuePress.
   *
   * ref：https://v1.vuepress.vuejs.org/theme/default-theme-config.html
   */
  themeConfig: {
    logo: '/img/logocentrado-preview.png',
    editLinks: false,
    docsDir: "",
    editLinkText: "",
    lastUpdated: false,
    header: {
      showTitle: false,
    },
    /*
    nav: [
      {
        text: "Guide",
        link: "/guide/",
      },
      {
        text: "Config",
        link: "/config/",
      },
      {
        text: "VuePress",
        link: "https://v1.vuepress.vuejs.org",
      },
    ],
    */
    sidebar: {
      '/guide/': [
        'Autenticación',
        {
          title: 'Ahorro Programado',
          collapsable: true,
          children: [
            'Ahorro Programado/Contratar Simulación', 
            'Ahorro Programado/Crear', 
            'Ahorro Programado/Modificar Cuenta Destino', 
            'Ahorro Programado/Modificar Cuenta Origen', 
            'Ahorro Programado/Modificar Fecha de Abono', 
            'Ahorro Programado/Modificar Meta de Ahorro', 
            'Ahorro Programado/Modificar Monto de Abono', 
            'Ahorro Programado/Obtener', 
            'Ahorro Programado/Obtener Cuentas Destino Habilitadas', 
            'Ahorro Programado/Obtener Cuentas Origen Habilitadas', 
            'Ahorro Programado/Obtener Documentos Digitales', 
            'Ahorro Programado/Obtener Estado de Cuenta', 
            'Ahorro Programado/Obtener Periodos Habilitados', 
            'Ahorro Programado/Obtener Plazos Habilitados', 
            'Ahorro Programado/Obtener Productos', 
            'Ahorro Programado/Simular'
          ],
        },
        {
          title: 'Cadena de Cierre',
          collapsable: true,
          children: [
            'Cadena de Cierre/Obtener Detalle de Ejecución', 
            'Cadena de Cierre/Obtener Detalle de Proceso', 
            'Cadena de Cierre/Obtener Procesos con Error', 
            'Cadena de Cierre/Obtener Procesos Críticos', 
            'Cadena de Cierre/Obtener Procesos Diarios', 
            'Cadena de Cierre/Obtener Procesos Mensuales', 
            'Cadena de Cierre/Obtener Procesos Reprocesables'
          ],
        },
        {
          title: 'Calendarios',
          collapsable: true,
          children: [
            'Calendarios/Calcular Fecha de Vencimiento', 
            'Calendarios/Calcular Fecha de Vencimiento en Días Hábiles', 
            'Calendarios/Calcular Plazo', 
            'Calendarios/Calcular Plazo en Días Hábiles', 
            'Calendarios/Obtener Fecha Hábil', 
            'Calendarios/Obtener Fecha Hábil Anterior', 
            'Calendarios/Obtener Fecha Hábil Anterior de Sucursal', 
            'Calendarios/Obtener Fecha Hábil de Sucursal', 
            'Calendarios/Obtener Inicio y Fin de Mes', 
            'Calendarios/Obtener Inicio y Fin de Mes de Sucursal', 
            'Calendarios/Obtener Próxima Fecha Hábil', 
            'Calendarios/Obtener Próxima Fecha Hábil de Sucursal' 
          ],
        },
        {
          title: 'CASH Management',
          collapsable: true,
          children: [
            'CASH Management/Alta Automática Contrato', 
            'CASH Management/Autorizar Archivo', 
            'CASH Management/Autorizar Orden', 
            'CASH Management/Cargar Archivo', 
            'CASH Management/Cargar Archivo Recibido Como Dato', 
            'CASH Management/Cargar Servicios Disponibles', 
            'CASH Management/Detener Archivo', 
            'CASH Management/Ingresar Orden Pago', 
            'CASH Management/Obtener Detalle de Orden de Cuenta', 
            'CASH Management/Obtener Detalle de Pago', 
            'CASH Management/Obtener Servicios', 
            'CASH Management/Obtener Valores Orden', 
            'CASH Management/Procesar Orden', 
            'CASH Management/Rechazar Archivo', 
            'CASH Management/Rechazar Orden', 
            'CASH Management/Visualizar Lista Resumen Cabezal', 
            'CASH Management/Visualizar Orden de Archivo Para Cuenta', 
            'CASH Management/Visualizar Resultado Procesamiento', 
            'CASH Management/Visualizar Resumen Cabezal', 
            'CASH Management/Visualizar Situacion Archivos', 
            'CASH Management/Visualizar Situacion Lineas' 
          ],
        },
        {
          title: 'Clientes',
          collapsable: true,
          children: [
            'Clientes/Actualizar', 
            'Clientes/Actualizar Documento Digital', 
            'Clientes/Actualizar Domicilio', 
            'Clientes/Actualizar Información Adicional', 
            'Clientes/Actualizar Teléfono', 
            'Clientes/Agregar Domicilio', 
            'Clientes/Agregar Información Adicional', 
            'Clientes/Agregar Integrante', 
            'Clientes/Agregar Telefono', 
            'Clientes/Asociar Documento Digital', 
            'Clientes/Crear', 
            'Clientes/Crear con Persona Existente', 
            'Clientes/Crear Para Persona Jurídica', 
            'Clientes/Eliminar Documento Digital', 
            'Clientes/Eliminar Domicilio', 
            'Clientes/Eliminar Información Adicional', 
            'Clientes/Eliminar Integrante', 
            'Clientes/Habilitar', 
            'Clientes/Inhabilitar', 
            'Clientes/Modificar Ejecutivo', 
            'Clientes/Obtener', 
            'Clientes/Obtener Ahorros Programados', 
            'Clientes/Obtener Bolsillos', 
            'Clientes/Obtener Clasificaciones Internas', 
            'Clientes/Obtener Cuenta Cliente', 
            'Clientes/Obtener Cuentas de Ahorro (Saldo Contable)', 
            'Clientes/Obtener Cuentas de Ahorro (Saldo Disponible)', 
            'Clientes/Obtener Cuentas Corrientes (Saldo Contable)', 
            'Clientes/Obtener Cuentas Corrientes (Saldo Disponible)', 
            'Clientes/Obtener Datos', 
            'Clientes/Obtener Documento Digital', 
            'Clientes/Obtener Documentos Digitales', 
            'Clientes/Obtener Domicilios', 
            'Clientes/Obtener Facultades', 
            'Clientes/Obtener Identificador Único', 
            'Clientes/Obtener Información Adicional', 
            'Clientes/Obtener Integrantes', 
            'Clientes/Obtener Límites', 
            'Clientes/Obtener Motivos Inhabilitacion', 
            'Clientes/Obtener Perfil', 
            'Clientes/Obtener Plazos Fijos Cancelados', 
            'Clientes/Obtener Plazos Fijos con Avance', 
            'Clientes/Obtener Plazos Fijos', 
            'Clientes/Obtener Préstamos', 
            'Clientes/Obtener Préstamos Cancelados', 
            'Clientes/Obtener Préstamos Castigados', 
            'Clientes/Obtener Préstamos con Avance', 
            'Clientes/Obtener Resumen por Producto a Cierre Año', 
            'Clientes/Obtener Resumen de Productos (Saldos Contables)', 
            'Clientes/Obtener Resumen de Productos (Cierre de año)', 
            'Clientes/Obtener Resumen de Productos (Saldos Disponibles)', 
            'Clientes/Obtener Riesgo de Credito', 
            'Clientes/Obtener Saldos de Otros Productos', 
            'Clientes/Obtener Sectores', 
            'Clientes/Obtener Segmentos', 
            'Clientes/Obtener Tarjetas de Débito', 
            'Clientes/Obtener Telefonos', 
            'Clientes/Obtener Tipos de Integración', 
            'Clientes/Obtener Titular Representativo', 
            'Clientes/Validar Existencia', 
            'Clientes/Verificar Empleado'
          ],
        },
        {
          title: 'Configuración Bantotal',
          collapsable: true,
          children: [
            'Configuración Bantotal/Obtener Actividades', 
            'Configuración Bantotal/Obtener Actividades por Tipo', 
            'Configuración Bantotal/Obtener Agencias Banco', 
            'Configuración Bantotal/Obtener Bancos', 
            'Configuración Bantotal/Obtener Barrios y Colonias', 
            'Configuración Bantotal/Obtener Calendario de Sucursal', 
            'Configuración Bantotal/Obtener Calendarios', 
            'Configuración Bantotal/Obtener Ciudades y Localidades', 
            'Configuración Bantotal/Obtener Códigos de Domicilio', 
            'Configuración Bantotal/Obtener Detalle de Calendario', 
            'Configuración Bantotal/Obtener Detalle de Calendario de Sucursal', 
            'Configuración Bantotal/Obtener Dólar USA', 
            'Configuración Bantotal/Obtener Ejecutivos', 
            'Configuración Bantotal/Obtener Empresa', 
            'Configuración Bantotal/Obtener Estados, Provincias y Departamentos', 
            'Configuración Bantotal/Obtener Estados', 
            'Configuración Bantotal/Obtener Fecha de Sistema', 
            'Configuración Bantotal/Obtener Impuestos', 
            'Configuración Bantotal/Obtener Instrucciones', 
            'Configuración Bantotal/Obtener Menús', 
            'Configuración Bantotal/Obtener Moneda Nacional', 
            'Configuración Bantotal/Obtener Monedas', 
            'Configuración Bantotal/Obtener Países', 
            'Configuración Bantotal/Obtener Paquetes', 
            'Configuración Bantotal/Obtener Perfiles', 
            'Configuración Bantotal/Obtener Pizarras', 
            'Configuración Bantotal/Obtener Pizarra por Módulo', 
            'Configuración Bantotal/Obtener Sucursales', 
            'Configuración Bantotal/Obtener Tipos de Actividad', 
            'Configuración Bantotal/Obtener Tipos de Documento Digital', 
            'Configuración Bantotal/Obtener Tipos de Telefono (Disponible únicamente para V2R3)', 
            'Configuración Bantotal/Obtener Tipos de Texto', 
            'Configuración Bantotal/Obtener Tipos de Listas Negras', 
            'Configuración Bantotal/Obtener Tipos de Tarjeta', 
            'Configuración Bantotal/Obtener Tipos de Vivienda'
          ],
        },
        {
          title: 'Contabilidad',
          collapsable: true,
          children: [
            'Contabilidad/Actualizar Condición Impositiva', 
            'Contabilidad/Agregar Texto Asiento', 
            'Contabilidad/Agregar Texto Ordinal', 
            'Contabilidad/Anular Movimiento', 
            'Contabilidad/Crear Condición Impositiva', 
            'Contabilidad/Obtener Cliente de una Operación', 
            'Contabilidad/Obtener Condición Impositiva', 
            'Contabilidad/Obtener Detalle de Movimiento', 
            'Contabilidad/Obtener Detalle de Ordinal', 
            'Contabilidad/Obtener Id Bantotal Movimiento', 
            'Contabilidad/Obtener Id Bantotal Operación', 
            'Contabilidad/Obtener Id Bantotal Producto', 
            'Contabilidad/Obtener Identificador Único de Movimiento', 
            'Contabilidad/Obtener Identificador Único de Operación', 
            'Contabilidad/Obtener Identificador Único de Producto', 
            'Contabilidad/Obtener Integrantes de Operación', 
            'Contabilidad/Obtener Textos de Movimiento', 
            'Contabilidad/Registrar Asiento', 
            'Contabilidad/Registrar Asiento Fecha Valor'
          ],
        },
        {
          title: 'Cuentas Corrientes',
          collapsable: true,
          children: [
            'Cuentas Corrientes/Anular Cheque Electrónico', 
            'Cuentas Corrientes/Asignar Id a Cheque Electrónico', 
            'Cuentas Corrientes/Contratar Producto con Alta de Facultades', 
            'Cuentas Corrientes/Contratar con Periodicidad', 
            'Cuentas Corrientes/Contratar Producto', 
            'Cuentas Corrientes/Crear Chequera Electrónica', 
            'Cuentas Corrientes/Depositar Cheque Electrónico de Otro Banco', 
            'Cuentas Corrientes/Depositar Cheque Electrónico en Custodia', 
            'Cuentas Corrientes/Depositar Cheque Electrónico de Banco Propio', 
            'Cuentas Corrientes/Eliminar Chequera', 
            'Cuentas Corrientes/Emitir Cheque Electronico', 
            'Cuentas Corrientes/Emitir Cheque Electrónico de Chequera', 
            'Cuentas Corrientes/Habilitar Cheque Electronico', 
            'Cuentas Corrientes/Obtener Chequera', 
            'Cuentas Corrientes/Obtener Chequeras', 
            'Cuentas Corrientes/Obtener Cheques de Chequera', 
            'Cuentas Corrientes/Obtener Comisión Chequera', 
            'Cuentas Corrientes/Obtener Datos', 
            'Cuentas Corrientes/Obtener Estado de Chequera', 
            'Cuentas Corrientes/Obtener Estado de Cuenta', 
            'Cuentas Corrientes/Obtener Evolucion de Saldos', 
            'Cuentas Corrientes/Obtener Productos', 
            'Cuentas Corrientes/Obtener Solicitudes de Chequeras', 
            'Cuentas Corrientes/Obtener Tipos de Chequera', 
            'Cuentas Corrientes/Obtener Tipos de Chequera por Producto', 
            'Cuentas Corrientes/Registrar Orden de No Pago de Chequera', 
            'Cuentas Corrientes/Registrar Orden de No Pago de Cheques', 
            'Cuentas Corrientes/Solicitar Chequera'
          ],
        },
        {
          title: 'Cuentas de Ahorro',
          collapsable: true,
          children: [
            'Cuentas de Ahorro/Contratar Producto con Alta de Facultades', 
            'Cuentas de Ahorro/Contratar con Periodicidad', 
            'Cuentas de Ahorro/Contratar Producto', 
            'Cuentas de Ahorro/Obtener Datos', 
            'Cuentas de Ahorro/Obtener Estado de Cuenta', 
            'Cuentas de Ahorro/Obtener Evolución de Saldos', 
            'Cuentas de Ahorro/Obtener Productos'    
          ],
        },
        {
          title: 'Cuentas Vista',
          collapsable: true,
          children: [
            'Cuentas Vista/Activar', 
            'Cuentas Vista/Actualizar Documento Digital', 
            'Cuentas Vista/Actualizar Período de Acreditación', 
            'Cuentas Vista/Agregar Beneficiario', 
            'Cuentas Vista/Asociar Documento Digital', 
            'Cuentas Vista/Bloquear Saldo', 
            'Cuentas Vista/Cancelar', 
            'Cuentas Vista/Desbloquear Saldo', 
            'Cuentas Vista/Eliminar Documento Digital', 
            'Cuentas Vista/Obtener Bolsillos', 
            'Cuentas Vista/Obtener CBU de Cuenta Vista', 
            'Cuentas Vista/Obtener Cuenta Vista de CBU', 
            'Cuentas Vista/Obtener Detalle Bloqueo', 
            'Cuentas Vista/Obtener Documento Digital', 
            'Cuentas Vista/Obtener Documentos Digitales', 
            'Cuentas Vista/Obtener Estado de Cuenta por Período', 
            'Cuentas Vista/Obtener Facultades', 
            'Cuentas Vista/Obtener Paquete', 
            'Cuentas Vista/Obtener Período de Acreditación', 
            'Cuentas Vista/Obtener Periodos de Acreditación', 
            'Cuentas Vista/Obtener Saldo Bloqueado', 
            'Cuentas Vista/Obtener Saldo Disponible', 
            'Cuentas Vista/Traspasar Entre Cuentas de la Misma Persona', 
            'Cuentas Vista/Traspasar Entre Cuentas Propias', 
            'Cuentas Vista/Traspasar Entre Cuentas Propias (con tipo de cambio)', 
            'Cuentas Vista/Traspasar Entre Cuentas Propias (diferentes monedas)', 
            'Cuentas Vista/Traspasar Entre Cuentas Terceros', 
            'Cuentas Vista/Traspasar Entre Cuentas Terceros (con tipo de cambio)', 
            'Cuentas Vista/Traspasar Entre Cuentas Terceros (diferentes monedas)', 
            'Cuentas Vista/Traspasar Entre Cuentas Mismo Titular (con tipo de cambio)', 
            'Cuentas Vista/Traspasar Entre Cuentas Mismo Titular (diferentes monedas)' 
          ],
        },
        {
          title: 'Depósitos a Plazo',
          collapsable: true,
          children: [
            'Depósitos a Plazo/Contratar', 
            'Depósitos a Plazo/Contratar Simulación', 
            'Depósitos a Plazo/Modificar Cuenta Destino de Acreditación Periódica', 
            'Depósitos a Plazo/Modificar Cuenta Destino al Vencimiento', 
            'Depósitos a Plazo/Modificar Instrucción', 
            'Depósitos a Plazo/Obtener Avance', 
            'Depósitos a Plazo/Obtener Datos', 
            'Depósitos a Plazo/Obtener Documentos Digitales', 
            'Depósitos a Plazo/Obtener Instrucción', 
            'Depósitos a Plazo/Obtener Instrucciones Habilitados', 
            'Depósitos a Plazo/Obtener Movimientos', 
            'Depósitos a Plazo/Obtener Periodos Habilitados', 
            'Depósitos a Plazo/Obtener Productos', 
            'Depósitos a Plazo/Obtener Productos Habilitados', 
            'Depósitos a Plazo/Obtener Tasa de Precancelación', 
            'Depósitos a Plazo/Simular', 
            'Depósitos a Plazo/Simular Con Cronograma',   
          ],
        },
        {
          title: 'Descuento de Documentos',
          collapsable: true,
          children: [
            'Descuento de Documentos/Confirmar Lista', 
            'Descuento de Documentos/Crear Lista', 
            'Descuento de Documentos/Crear Lista Cheques', 
            'Descuento de Documentos/Obtener Productos', 
            'Descuento de Documentos/Seleccionar Opcion Desembolso'
          ],
        },
        {
          title: 'Indicadores',
          collapsable: true,
          children: [
            'Indicadores/Obtener Agrupadores', 
            'Indicadores/Obtener Cierre de Saldos por Moneda', 
            'Indicadores/Obtener Condiciones Generales', 
            'Indicadores/Obtener Indicadores', 
            'Indicadores/Obtener Monedas Indices', 
            'Indicadores/Obtener Rubros Bolsa', 
            'Indicadores/Obtener Sucursales Cajas', 
            'Indicadores/Obtener Transacciones por Estados',   
          ],
        },
        {
          title: 'Microfinanzas',
          collapsable: true,
          children: [
            'Microfinanzas/Actualizar Grupo', 
            'Microfinanzas/Actualizar Integrante de Grupo', 
            'Microfinanzas/Agregar Fiador', 
            'Microfinanzas/Agregar Grupo', 
            'Microfinanzas/Agregar Integrante a Grupo', 
            'Microfinanzas/Agregar Operaciones a Cancelar', 
            'Microfinanzas/Buscar Cliente', 
            'Microfinanzas/Completar Tarea', 
            'Microfinanzas/Crear Solicitud Ampliación', 
            'Microfinanzas/Crear Solicitud Grupal', 
            'Microfinanzas/Crear Solicitud Individual', 
            'Microfinanzas/Crear Solicitud Renovación', 
            'Microfinanzas/Eliminar Fiador', 
            'Microfinanzas/Habilita Integrante de un Grupo', 
            'Microfinanzas/Inabilita Integrante de un Grupo', 
            'Microfinanzas/Obtener Asesores', 
            'Microfinanzas/Obtener Campañas', 
            'Microfinanzas/Obtener Destinos Crédito', 
            'Microfinanzas/Obtener Detalle Grupo', 
            'Microfinanzas/Obtener Grupos', 
            'Microfinanzas/Obtener Integrantes de Grupo', 
            'Microfinanzas/Obtener Operaciones a Cancelar', 
            'Microfinanzas/Obtener Operaciones Cliente', 
            'Microfinanzas/Obtener Origenes de Captación', 
            'Microfinanzas/Obtener Productos', 
            'Microfinanzas/Obtener Solicitudes Cliente', 
            'Microfinanzas/Obtener Tipos Aval', 
            'Microfinanzas/Obtener Tipos de Integrante', 
            'Microfinanzas/Obtener Tipos de Grupo', 
            'Microfinanzas/Quitar Operaciones a Cancelar', 
            'Microfinanzas/Simular Préstamo Amortizable', 
            'Microfinanzas/Simular Préstamo Amortizable Grupal', 
            'Microfinanzas/Simular Libre Amortización', 
            'Microfinanzas/Simular Préstamo Plazo Fijo', 
            'Microfinanzas/Validar Políticas', 

          ],
        },
        {
          title: 'Modelador de Préstamos',
          collapsable: true,
          children: [
            'Modelador de Préstamos/Obtener Cantidad Cuotas', 
            'Modelador de Préstamos/Obtener Capital', 
            'Modelador de Préstamos/Obtener Comisiones', 
            'Modelador de Préstamos/Obtener Comisiones por Cuota', 
            'Modelador de Préstamos/Obtener Días Primer Período', 
            'Modelador de Préstamos/Obtener Período Entre Cuotas', 
            'Modelador de Préstamos/Obtener Permite Seguros del Mismo Tipo', 
            'Modelador de Préstamos/Obtener Plazo', 
            'Modelador de Préstamos/Obtener Requiere Seguro de Vida Obligatorio', 
            'Modelador de Préstamos/Obtener Seguros'
          ],
        },
        {
          title: 'PAE',
          collapsable: true,
          children: [
            'PAE/Obtener Items Modelo', 
            'PAE/Obtener Modelos PAE', 
            'PAE/Obtener Scores', 
            'PAE/Obtener Tipos De Modelos'  
          ],
        },
        {
          title: 'Parámetros Base',
          collapsable: true,
          children: [
            'Parámetros Base/Obtener Correlativo Guía Especial', 
            'Parámetros Base/Obtener Correlativo Guía', 
            'Parámetros Base/Obtener Guía de Proceso', 
            'Parámetros Base/Obtener Guía Especial de Proceso', 
            'Parámetros Base/Obtener Opcion General de Proceso', 
            'Parámetros Base/Obtener Opción General Por Modulo', 
            'Parámetros Base/Obtener Programa Particular'
          ],
        },
        {
          title: 'Personas',
          collapsable: true,
          children: [
            'Personas/Actualizar', 
            'Personas/Actualizar Celular', 
            'Personas/Actualizar Contacto', 
            'Personas/Actualizar Cónyuge', 
            'Personas/Actualizar Correo Electrónico', 
            'Personas/Actualizar Documento Digital', 
            'Personas/Actualizar Domicilio', 
            'Personas/Actualizar FATCA', 
            'Personas/Actualizar Información Adicional', 
            'Personas/Actualizar Información Financiera', 
            'Personas/Actualizar Integrante de Persona Jurídica', 
            'Personas/Actualizar Persona Jurídica', 
            'Personas/Actualizar Profesión', 
            'Personas/Actualizar Referencia', 
            'Personas/Actualizar Teléfono', 
            'Personas/Actualizar Víctima Hecho Violento', 
            'Personas/Agregar a Lista Negra', 
            'Personas/Agregar Contacto', 
            'Personas/Agregar Datos PEP', 
            'Personas/Agregar Documento Adicional', 
            'Personas/Agregar Domicilio', 
            'Personas/Agregar FATCA', 
            'Personas/Agregar Información Adicional', 
            'Personas/Agregar Información Financiera', 
            'Personas/Agregar Integrante a Persona Jurídica', 
            'Personas/Agregar Persona Vinculada', 
            'Personas/Agregar Referencia', 
            'Personas/Agregar Teléfono', 
            'Personas/Agregar Víctima Hecho Violento', 
            'Personas/Asociar Documento Digital', 
            'Personas/Crear', 
            'Personas/Crear Cónyuge', 
            'Personas/Crear Persona Jurídica', 
            'Personas/Crear Reducido', 
            'Personas/Eliminar Cónyuge', 
            'Personas/Eliminar Documento Adicional', 
            'Personas/Eliminar Documento Digital', 
            'Personas/Eliminar Domicilio', 
            'Personas/Eliminar Información Adicional', 
            'Personas/Eliminar Integrante de Persona Jurídica', 
            'Personas/Eliminar Persona Vinculada', 
            'Personas/Eliminar Profesión', 
            'Personas/Evaluar PAE', 
            'Personas/Modificar Documento Adicional', 
            'Personas/Obtener', 
            'Personas/Obtener Concepto', 
            'Personas/Obtener Contactos', 
            'Personas/Obtener Cónyuge', 
            'Personas/Obtener Correos Electrónicos', 
            'Personas/Obtener Cuentas Cliente', 
            'Personas/Obtener Datos PEP', 
            'Personas/Obtener Documento Digital', 
            'Personas/Obtener Documentos Adicionales', 
            'Personas/Obtener Documentos Digitales', 
            'Personas/Obtener Domicilios', 
            'Personas/Obtener Estados Civiles', 
            'Personas/Obtener Facultades', 
            'Personas/Obtener FATCA', 
            'Personas/Obtener Hobbies', 
            'Personas/Obtener Hobby', 
            'Personas/Obtener Id Bantotal', 
            'Personas/Obtener Identificador Único', 
            'Personas/Obtener Identidades de Género', 
            'Personas/Obtener Información Adicional', 
            'Personas/Obtener Información Financiera', 
            'Personas/Obtener Integrantes Persona Jurídica', 
            'Personas/Obtener Naturalezas Jurídicas', 
            'Personas/Obtener Niveles Educativos', 
            'Personas/Obtener Ocupaciones', 
            'Personas/Obtener Persona Jurídica', 
            'Personas/Obtener Personas', 
            'Personas/Obtener Personas Jurídicas', 
            'Personas/Obtener Personas Vinculadas', 
            'Personas/Obtener Profesión', 
            'Personas/Obtener Profesiones', 
            'Personas/Obtener Referencias', 
            'Personas/Obtener Tarjetas de Débito', 
            'Personas/Obtener Teléfono', 
            'Personas/Obtener Teléfonos', 
            'Personas/Obtener Tipo de Persona', 
            'Personas/Obtener Tipos de Documento', 
            'Personas/Obtener Víctima Hecho Violento', 
            'Personas/Obtener Vínculos', 
            'Personas/Obtener Vínculos de Afinidad', 
            'Personas/Obtener Vínculos de Consanguinidad', 
            'Personas/Obtener Vínculos Juridicos', 
            'Personas/Validar Documento', 
            'Personas/Validar en Listas Negras', 
            'Personas/Validar Existencia', 
            'Personas/Validar Listas Inhabilitados'
          ],
        },
        {
          title: 'Precios',
          collapsable: true,
          children: [
            'Precios/Convertir Tasa Anual Efectiva a Lineal', 
            'Precios/Convertir Tasa Anual Lineal a Efectiva', 
            'Precios/Convertir Tasa Mensual Efectiva a Lineal', 
            'Precios/Convertir Tasa Mensual Lineal a Efectiva', 
            'Precios/Obtener Cotización a Fecha', 
            'Precios/Obtener Cotización Cierre', 
            'Precios/Obtener Cotización', 
            'Precios/Obtener Pizarra Especial por Transacción', 
            'Precios/Obtener Precio a Fecha', 
            'Precios/Obtener Precio Especie', 
            'Precios/Obtener Tasa Para Cliente', 
            'Precios/Obtener Tasa de Operación', 
            'Precios/Obtener Tasa Para Producto', 
            'Precios/Obtener Tipo de Cambio'
          ],
        },
        {
          title: 'Préstamos',
          collapsable: true,
          children: [
            'Préstamos/Abonar a Cuenta', 
            'Préstamos/Actualizar Documento Digital', 
            'Préstamos/Actualizar Información Adicional', 
            'Préstamos/Actualizar Prestamos con Evento (Disponible únicamente para V3R1)', 
            'Préstamos/Agregar Cuenta de Cobro', 
            'Préstamos/Agregar Información Adicional', 
            'Préstamos/Asociar Documento Digital', 
            'Préstamos/Cancelar', 
            'Préstamos/Cancelar a Fecha', 
            'Préstamos/Cancelar a Fecha Terceros', 
            'Préstamos/Cancelar Terceros', 
            'Préstamos/Contratar', 
            'Préstamos/Contratar Ampliación', 
            'Préstamos/Contratar Refinanciación por Deuda Total', 
            'Préstamos/Contratar Refinanciación por Saldo Capital', 
            'Préstamos/Eliminar Cuenta de Cobro', 
            'Préstamos/Eliminar Documento Digital', 
            'Préstamos/Eliminar Información Adicional', 
            'Préstamos/Obtener Cronograma', 
            'Préstamos/Obtener Cronograma a Fecha', 
            'Préstamos/Obtener Cronograma con Pagos a Fecha', 
            'Préstamos/Obtener Cronograma en Especie', 
            'Préstamos/Obtener Cronograma Original', 
            'Préstamos/Obtener Cuenta de Cobro', 
            'Préstamos/Obtener Datos del Próximo Vencimiento', 
            'Préstamos/Obtener Detalle', 
            'Préstamos/Obtener Detalle a Fecha', 
            'Préstamos/Obtener Detalle de Oferta', 
            'Préstamos/Obtener Detalle de Oferta Amortizable', 
            'Préstamos/Obtener Detalle de Préstamo Cancelado', 
            'Préstamos/Obtener Detalle Pago Préstamo', 
            'Préstamos/Obtener Detalle Reducido', 
            'Préstamos/Obtener Detalle Simulación', 
            'Préstamos/Obtener Deuda', 
            'Préstamos/Obtener Deuda Préstamo Castigado', 
            'Préstamos/Obtener Deuda Vencida', 
            'Préstamos/Obtener Documento Digital', 
            'Préstamos/Obtener Documentos Digitales', 
            'Préstamos/Obtener Fecha de Incumplimiento', 
            'Préstamos/Obtener Fechas de Pago', 
            'Préstamos/Obtener Fecha de Ultimo Pago', 
            'Préstamos/Obtener Información Adicional', 
            'Préstamos/Obtener Monto de Cancelación', 
            'Préstamos/Obtener Pagos de un Préstamo', 
            'Préstamos/Obtener Pagos de Cuota', 
            'Préstamos/Obtener Prestamos a Vencer (Disponible únicamente para V3R1)', 
            'Préstamos/Obtener Prestamos por Rango Mora (Disponible únicamente para V3R1)', 
            'Préstamos/Obtener Prestamos sin Mora (Disponible únicamente para V3R1)', 
            'Préstamos/Obtener Productos', 
            'Préstamos/Pagar Cuota', 
            'Préstamos/Pagar Cuota a Fecha', 
            'Préstamos/Pagar Cuota a Fecha Terceros', 
            'Préstamos/Pagar Cuota Terceros', 
            'Préstamos/Simular', 
            'Préstamos/Simular Amortizable Sin Cliente', 
            'Préstamos/Simular Ampliación', 
            'Préstamos/Simular Ampliación Ingresando Seguros', 
            'Préstamos/Simular Despejando Capital y Cantidad de Cuotas', 
            'Préstamos/Simular Despejando Capital y Cantidad de Cuotas Sin Cliente', 
            'Préstamos/Simular Despejando Fecha de Vencimiento y Cantidad de Cuotas', 
            'Préstamos/Simular Despejando Fecha de Vencimiento y Cantidad de Cuotas Sin Cliente', 
            'Préstamos/Simular Despejando Fecha de Vencimiento y Tasa', 
            'Préstamos/Simular Despejando Fecha de Vencimiento y Tasa Sin Cliente', 
            'Préstamos/Simular Ingresando Balloon', 
            'Préstamos/Simular Ingresando Balloon Sin Cliente', 
            'Préstamos/Simular Ingresando Seguros', 
            'Préstamos/Simular Ingresando Seguros Sin Cliente', 
            'Préstamos/Simular Libre Amortización', 
            'Préstamos/Simular Libre Amortización Sin Cliente', 
            'Préstamos/Simular Ofertas', 
            'Préstamos/Simular Plazo Fijo', 
            'Préstamos/Simular Refinanciación por Deuda Total', 
            'Préstamos/Simular Refinanciación por Saldo Capital'
          ],
        },
        {
          title: 'Reglas de Negocio',
          collapsable: true,
          children: [
            'Reglas de Negocio/Evaluar Regla de Negocio', 
            'Reglas de Negocio/Obtener Reglas de Negocio', 
            'Reglas de Negocio/Obtener Variables Regla', 
            'Reglas de Negocio/Validar Datos Regla de Negocio'
          ],
        },
        {
          title: 'Seguridad',
          collapsable: true,
          children: [
            'Seguridad/Autorizar Excepción', 
            'Seguridad/Obtener Detalle de Excepción', 
            'Seguridad/Obtener Excepciones', 
            'Seguridad/Rechazar Excepcion', 
            'Seguridad/Registrar Dispositivo'
          ],
        },
        {
          title: 'Tarjetas de Débito',
          collapsable: true,
          children: [
            'Tarjetas de Débito/Activar Tarjeta', 
            'Tarjetas de Débito/Actualizar Cuenta Preferencial', 
            'Tarjetas de Débito/Asociar Cuenta', 
            'Tarjetas de Débito/Blanqueo de Pin', 
            'Tarjetas de Débito/Bloqueo de Tarjeta', 
            'Tarjetas de Débito/Crear', 
            'Tarjetas de Débito/Denunciar Tarjeta', 
            'Tarjetas de Débito/Desbloqueo de Tarjeta', 
            'Tarjetas de Débito/Eliminar Cuenta Asociada', 
            'Tarjetas de Débito/Modificar Límite', 
            'Tarjetas de Débito/Obtener Códigos de Limites', 
            'Tarjetas de Débito/Obtener Cuenta Preferencial',
            'Tarjetas de Débito/Obtener Cuentas a Asociar',
            'Tarjetas de Débito/Obtener Cuentas Asociadas Por Tipo', 
            'Tarjetas de Débito/Obtener Cuentas Asociadas', 
            'Tarjetas de Débito/Obtener Datos', 
            'Tarjetas de Débito/Obtener Identificador Unico', 
            'Tarjetas de Débito/Obtener Límites', 
            'Tarjetas de Débito/Obtener Motivos de Bloqueo', 
            'Tarjetas de Débito/Obtener Movimientos', 
            'Tarjetas de Débito/Obtener Tarjeta', 
            'Tarjetas de Débito/Obtener Tarjeta Habiente', 
            'Tarjetas de Débito/Obtener Tarjetas Adicionales', 
            'Tarjetas de Débito/Obtener Tipos de Cuenta'
          ],
        },
        {
          title: 'Usuarios',
          collapsable: true,
          children: [
            'Usuarios/Agregar Perfil', 
            'Usuarios/Crear', 
            'Usuarios/Eliminar Perfil', 
            'Usuarios/Eliminar Usuario', 
            'Usuarios/Habilitar Usuario', 
            'Usuarios/Inhabilitar Usuario', 
            'Usuarios/Modificar', 
            'Usuarios/Obtener', 
            'Usuarios/Obtener Perfiles', 
            'Usuarios/Obtener Usuarios', 
            'Usuarios/Obtener Usuarios Para Perfil'
          ],
        },
        {
          title: 'Workflow',
          collapsable: true,
          icon: false,
          children: [
            'Workflow/Obtener Metadata De Tarea', 
            'Workflow/Obtener Procesos Habilitados', 
            'Workflow/Obtener Roles', 
            'Workflow/Obtener Roles de Tarea', 
            'Workflow/Obtener Tareas de Proceso'
          ],
        }
      ]
    },
  },

  /**
   * Apply plugins，ref：https://v1.vuepress.vuejs.org/zh/plugin/
   */
  plugins: ["@vuepress/plugin-back-to-top", "@vuepress/plugin-medium-zoom"],
};
